##
# Automations that tigger when assignment of a user on an Issue occurs.
#
# To run this workflow locally via `act`, use the following commands. If you haven't authenticated with the appropriate
# scopes included in your login, as shown below, you need to reauthenticate before running this workflow:
#
# ```sh
# gh auth login -s "project"
# act -s GITHUB_TOKEN=$(gh auth token) -j auto-issue-assign-user issues
# ```
#
# The authentication command generally only needs to be ran once and then only if `act` asks for it.
#
# This *does* make changes on GitHub. Reserve Issue #1 and Pull Request #1 for testing purposes. To change this
# configuration, see the `.github/workflows/tests/payloads` directory.
#
# @see {@link https://docs.github.com/en/webhooks/webhook-events-and-payloads#issues}
#
---
name: Automation on Issue Assigned to User

on:
  ##
  # Run if assignment of an issue changes.
  #
  issues:
    types:
      - assigned

##
# All steps should have read-only access, unless explicitly given.
#
permissions: read-all

##
# Linting steps.
#
# @link https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
#
jobs:
  auto-issue-assign-user:
    name: Update Issue Labels
    runs-on: ubuntu-latest

    ##
    # This job's `GITHUB_TOKEN` or `PAT` must have these permissions.
    #
    # Always aim to provide as few permissions as possible for personal access tokens.
    #
    # @link https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    #
    permissions:
      issues: write

    steps:
      ##
      # Checkout the Repository workflow source.
      #
      - name: Checkout Repository workflow source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |-
            .github/workflows

      ##
      # Update the labels on the issue based on the action and the state.
      #
      # @link https://github.com/actions/github-script
      #
      - name: Update labels based on state
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

          script: |-
            require(".github/workflows/src/ActionContext").init(
              github, context, core, glob, io, exec, fetch
            );

            require(".github/workflows/src/Automation/OnIssues")
              .handleUserAssigned();
